    {
    console.log('sa');
    ;
    ;
    ;
    ;
    ;
    ;
    console.log('ss');
    //bloco de codigo
    {
        {
            {
                {
                    {
                        {
                            {
                                {
                                    console.log('teste ansdasds');
                                    {
                                        {
                                            {
                                                {
                                                    {
                                                        {
                                                            {
                                                            {
                                                                {
                                                                    {
                                                                        {
                                                                            {
                                                                                {
                                                                                    {
                                                                                        {
                                                                                            {
                                                                                                {
                                                                                                    {
                                                                                                        {
                                                                                                            {
                                                                                                                {
                                                                                                                    {
                                                                                                                        {
                                                                                                                            {
                                                                                                                                {
                                                                                                                                    console.log('sds');
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                            }

                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    }
    /*
    *
    *
    *
    *
    *
    *
    *
    *
    *
    */

